Update ispisivanje_rijeci_for_loop.cpp
Mirixy17/MindPower pull request #2
Opened 2020-05-28 08:51 UTC by Mirixy17

// je li moguce u ovu pricu involvirati SPACE izmedju imena i prezimena?

#include <iostream>

int main()
{
	int broj = 0;

	std::string rijec;
	std::cin >> rijec;

	for (rijec[broj]; broj < rijec.size(); broj++) 
	{
		std::cout << rijec[broj] << "\n";

	}
}

2020-05-28 11:25 UTC, lukarolak requested changes

2020-05-28 11:25 UTC, lukarolak commented on 3 primjeri/ispisivanje_rijeci_for_loop.cpp
> +	for (rijec[broj]; broj < rijec.size(); broj++)
Prvi dio for petlje izvodi kod, koji se dogodi prije drugog dijela.

u svom privom dijelu si napisala rijec[broj];
sto je jednako ovome kodu
`3;`

Napisao sam ti clanak o for petljama, procitaj ga. Mislim da dobro objasnjava 1, 2 i 3ci dio for petlje
https://github.com/Mirixy17/MindPower/wiki/for-loop

Htio bih da prepravis svoj kod tako da ne napises prvi dio for petlje ovako:
`for (; broj < rijec.size(); broj++) `
Posto nista ne radis u prvom dijelu petlje ovo je idealna perpravka

Standard u programiranju je da se tvoja for petlja napise ovako
`for (int broj = 0; broj < rijec.size(); broj++) `

Sada kreiras varijablu broj unutar for petlje(gdje je jedino i koristis)
Posto je varijabla kreirana u for petlji, mozes maknuti kreaciju varijable iz linije 5

Slobodno komentiraj na ovaj komentar ako ti nesto nije jasno.

2020-05-28 11:34 UTC, lukarolak commented
> // je li moguce u ovu pricu involvirati SPACE izmedju imena i prezimena?
> 
> #include
> 
> int main()
> {
> int broj = 0;
> 
> ```
> std::string rijec;
> std::cin >> rijec;
> 
> for (rijec[broj]; broj < rijec.size(); broj++) 
> {
> 	std::cout << rijec[broj] << "\n";
> 
> }
> ```
> 
> }

Aha.. primijetila si ako probas napisati space da ce se ispisati samo prva rijeci. std::cin prestaje upisivati znakove u string varijablu kada vidi space. Probaj koristiti naredbu spomenutu u ovom komentaru https://stackoverflow.com/a/26407065

2020-05-29 19:39 UTC, Mirixy17 commented
#include <iostream>

int main()
{

	std::string rijec;
	std::cin >> rijec;

	for (int broj = 0; broj < rijec.size(); broj++)
	{
		std::cout << rijec[broj] << "\n";
	}
}

2020-05-30 07:40 UTC, lukarolak approved these changes

2020-05-30 07:42 UTC, merged